import streamlit as st
import google.generativeai as genai
import os
from fpdf import FPDF

# --- CONFIG & AI SETUP ---
# PASTE YOUR API KEY BELOW
os.environ["GEMINI_API_KEY"] = "AIzaSyBPMOsT3zU8ZXjbK2_IRpmuJcSXJxOdLNg"
genai.configure(api_key=os.environ["AIzaSyBPMOsT3zU8ZXjbK2_IRpmuJcSXJxOdLNg"])
model = genai.GenerativeModel('gemini-1.5-flash-lates')

st.set_page_config(page_title="CURA - AI Health", layout="centered")

if 'page' not in st.session_state:
    st.session_state.page = 'landing'

# --- HELPER: PDF GENERATION ---
def create_pdf(name, score, bmi, analysis):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="CURA PERSONALIZED HEALTH REPORT", ln=True, align='C')
    
    pdf.set_font("Arial", size=12)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Patient Name: {name}", ln=True)
    pdf.cell(200, 10, txt=f"Health Risk Index: {score}/100", ln=True)
    pdf.cell(200, 10, txt=f"BMI: {bmi}", ln=True)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="AI Analysis & Recommendations:", ln=True)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 5, txt=analysis)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, txt="DISCLAIMER: This report is generated by AI for awareness purposes only. It is not a medical diagnosis. Please consult a licensed physician.")
    
    return pdf.output(dest='S').encode('latin-1')

# --- APP PAGES ---
if st.session_state.page == 'landing':
    st.title("🏥 CURA")
    st.subheader("Your Personal AI Health Risk Consultant")
    st.write("Get a medical-grade analysis of your lifestyle and health risks.")
    if st.button("Try CURA Now"):
        st.session_state.page = 'form'
        st.rerun()

elif st.session_state.page == 'form':
    st.title("Health Data Input")
    with st.form("cura_form"):
        name = st.text_input("Name")
        age = st.number_input("Age", 1, 120)
        weight = st.number_input("Weight (kg)")
        h_unit = st.radio("Height Unit", ["cm", "ft/in"])
        if h_unit == "cm":
            h = st.number_input("Height (cm)")
        else:
            ft = st.number_input("Feet", 1, 8)
            inch = st.number_input("Inches", 0, 11)
            h = (ft * 30.48) + (inch * 2.54)
            
        activity = st.selectbox("Activity Level", ["Very Low", "Low", "Moderate", "High", "Very High"])
        sleep = st.number_input("Sleep (hrs)", 0, 24)
        water = st.number_input("Water (Liters)", 0.0)
        habits = st.multiselect("Habits", ["Oily Food", "Red Meat", "High Sugar", "Alcohol", "Smoking"])
        history = st.text_area("Medical History/Past Issues")
        diabetic = st.radio("Diabetic?", ["No", "Yes", "Don't Know"])
        
        submitted = st.form_submit_button("Generate AI Report")
        
        if submitted:
            with st.spinner("AI is analyzing your patterns..."):
                bmi = round(weight / ((h/100)**2), 2)
                
                # CRAFTING THE AI PROMPT
                prompt = f"""
                Act as a medical-grade health consultant. Analyze this user data:
                Name: {name}, Age: {age}, BMI: {bmi}, Activity: {activity}, 
                Habits: {habits}, History: {history}, Diabetes: {diabetic}.
                
                1. Provide a Risk Index Score (0-100) where 100 is high risk.
                2. Identify specific personalized risk patterns based on their habits.
                3. Give 5 actionable lifestyle recommendations.
                Keep it professional and concise.
                """
                
                response = model.generate_content(prompt)
                st.session_state.analysis = response.text
                st.session_state.bmi = bmi
                st.session_state.name = name
                # Simple math for the meter (AI usually gives a number, but let's calculate a baseline)
                st.session_state.risk_score = 40 if bmi > 25 else 20
                st.session_state.page = 'results'
                st.rerun()

elif st.session_state.page == 'results':
    st.title("Your Health Analysis")
    st.metric("Risk Score", f"{st.session_state.risk_score}/100")
    st.progress(st.session_state.risk_score / 100)
    
    st.markdown(st.session_state.analysis)
    
    pdf_data = create_pdf(st.session_state.name, st.session_state.risk_score, st.session_state.bmi, st.session_state.analysis)
    st.download_button("Download Full PDF Report", data=pdf_data, file_name="CURA_Report.pdf", mime="application/pdf")
    
    if st.button("Start Over"):
        st.session_state.page = 'landing'
        st.rerun()
